#!/bin/bash
#PATH=/usr/local/sbin:/usr/sbin:/sbin:/usr/local/bin:/usr/bin:/bin
arrayStarted=true

# INCREMENTAL OR SYNC BACKUP TO UNRAID UNASSIGNED DEVICES -----------
# LINK: https://github.com/bdrtec/Unraid-Backup-Unassigned-Devices
# AUTHOR: BRAULIO DIAS RIBEIRO
# -------------------------------------------------------------------

# Turn on or off mount
St_Mount=0


# Fixed device to mount and backup ----------------------------
Fixed_Device=(
	# 1TB-ROTEADOR
	"sde"
	# 2TB-CASE-PTA
	"sdg"
)
# End Device fixed to mount and backup ------------------------


# Check if mount is turn on or off ----------------------------
if [ -n "${St_Mount}" ] && [ "${St_Mount}" -eq "1" ]; then
	i=0
	while [ $i -lt ${#Fixed_Device[@]} ]
	do
		/usr/local/emhttp/plugins/unassigned.devices/scripts/rc.unassigned mount "/dev/${Fixed_Device[$i]}1"
		let i++
	done
	echo "Mount successful!"
elif [ -z "${St_Mount}" ] || ([ "${St_Mount}" -ne "0" ] && [ "${St_Mount}" -ne "1" ]); then
	echo "Script not configured correctly! (set 0 or 1 in St_Mount)"
fi
# End Check if mount is turn on or off ------------------------
